### ISSUE TITLE
Failed building wheel for fastText (installation)

### ISSUE THREAD

**Issue by 19345Kris** [facebookresearch/fastText#775] opened 2019-04-01 13:23 UTC
When I try to install fastText using `pip install fasttext` I get the following error:

/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I./fasttext -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c fasttext/cpp/src/vector.cc -o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/vector.o -O3 -pthread -funroll-loops -std=c++0x -stdlib=libc++ -mmacosx-version-min=10.7
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I./fasttext -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c fasttext/cpp/src/main.cc -o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/main.o -O3 -pthread -funroll-loops -std=c++0x -stdlib=libc++ -mmacosx-version-min=10.7
    g++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/fasttext/fasttext.o build/temp.macosx-10.6-intel-3.6/fasttext/interface.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/args.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/dictionary.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/matrix.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/model.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/utils.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/fasttext.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/vector.o build/temp.macosx-10.6-intel-3.6/fasttext/cpp/src/main.o -o build/lib.macosx-10.6-intel-3.6/fasttext/fasttext.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1

    
    ----------------------------------------

Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/zj/z4d6pnbj461cs58zwdrqmbc00000gn/T/pip-install-9lgkqrfj/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zj/z4d6pnbj461cs58zwdrqmbc00000gn/T/pip-record-w5elo89r/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zj/z4d6pnbj461cs58zwdrqmbc00000gn/T/pip-install-9lgkqrfj/fasttext/

I've tried to upgrade g++ using homebrew but it looks like I'm having other issues. 

I'm using mac OS mojave:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4) 
```
Could someone please help me out?

**Comment by soleares** [comment] 2019-04-04 06:13
Might be a duplicate of #753. This suggestion fixed it for me: https://github.com/facebookresearch/fastText/issues/753#issuecomment-476792284

**Comment by Celebio** [comment] 2019-07-09 09:13
Hi @19345Kris ,
The issue should be fixed now. 

Thank you very much for reporting it.
I am closing this issue. Feel free to re-open it if you observe the issue again.

Best regards,
Onur

**Closed by Celebio** 2019-07-09 09:13 UTC
Labels: Build, Python, follow-up-after-fix

**Comment by TheTravellingSalesman** [comment] 2020-01-16 22:17
@Celebio 
This issue is persistent. I'm encountering this again when trying to install fasttext 0.8.3 on an environment using cython 0.25.2 and python 3.6.

I've tried all of the linked solutions to no avail. Is there a way to get this working?

**Comment by jaogye** [comment] 2021-02-20 08:55
Hi @Celebio,

I report the same isse. I can not install fasttext in anaconda .

Best,
Juan

**Comment by bouyeijiang** [comment] 2021-11-20 14:57
i can't install fasttext in win server 2008r2
