### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by WENGIF** [facebookresearch/fastText#362] opened 2017-11-15 10:48 UTC
I use `fasttext.supervised()` to train my model. But when I set `word_ngrams=2`, the program occur
 a problem--` Floating point exception (core dumped)`. I don't kown why is it happend. thank you.

**Comment by cpuhrsch** [comment] 2017-11-15 16:33
Hello @WENGIF,

Thank you for your post. Judging by your syntax it looks like you're using third-party Python bindings. Are you able to reproduce this issue with the fasttext cli or our Python bindings? Also, could you provide a more detailed excerpt (OS, Python version, code snipped, etc.) so that I can try to reproduce this issue on my end?

Thanks,
Christian

**Comment by WENGIF** [comment] 2017-11-16 04:03
Hi @cpuhrsch ,
Thank you for your response. My detail environment as listed below:
Python version: Python 2.7.12
OS: ubuntu 16.04 LTS
OS-type: 64-bit
processor: Intel® Core™ i3-4160 CPU @ 3.60GHz × 4
Memory: 15.6 GiB
------
You can look at my detail  code:
`fasttext.supervised(TRAIN_DATA_FILE_PATH, MODEL_FASTTEXT_PATH, label_prefix='__label__', epoch=10, word_ngrams=2)`
Args:
    TRAIN_DATA_FILE_PATH: my train data which cut by 'jieba', for example `word1 word2 ... word_n\t__label__supervised_label\r\n`
    MODEL_FASTTEXT_PATH: use to store my bin model

**Comment by cpuhrsch** [comment] 2017-11-16 16:16
Hello @WENGIF,

Thank you for your detailed reply. It looks like you're using third-party Python bindings (please correct me if I'm wrong). Can you reproduce this error using the command line interface only or with our official Python bindings? Some third-party bindings use an old copy of the source-code.

Thanks,
Christian

**Comment by WENGIF** [comment] 2017-11-17 07:11
Hello @cpuhrsch,

Thanks for the suggestions. I git clone this repository in my environment. And try it again with the code `./fasttext supervised -input my_train_data_to_fasttext.txt -wordNgrams 2 -output ./my_model/model`.And this error disappear.
Summary follows:
I use the `https://pypi.tuna.tsinghua.edu.cn/simple/` to install fasttext and then appear this error. So, if we want to use fasttext, the best method is that git clone the repository from official address.

Thanks,
Christian

**Comment by cpuhrsch** [comment] 2017-11-17 21:43
Hello @WENGIF,

It sounds like the issue is with the python bindings then? If you want you could take a look at the Python bindings that are part of this repository. Since these are in beta stage we'd be happy to hear any feedback about them. I'm going to close this issue now as I interpret it as resolved, but please feel free to correct me and reopen it any point.

Thanks,
Christian

**Closed by cpuhrsch** 2017-11-17 21:43 UTC

**Comment by WENGIF** [comment] 2017-11-20 06:31
Hello @cpuhrsch,

Yes, I will. Anyway, thank you very much.

Thanks,
Christian
