### ISSUE TITLE
Website includes note to writer to include description of hierarchical softmax.

### ISSUE THREAD

**Issue by alexmarchant** [facebookresearch/fastText#599] opened 2018-08-01 14:12 UTC
![image](https://user-images.githubusercontent.com/953244/43526932-54351ed8-9573-11e8-819a-7b8265606855.png)

**Comment by Celebio** [comment] 2018-12-04 16:02
Hi @alexmarchant ,
Thank you for reporting the issue.
This is duplicate of https://github.com/facebookresearch/fastText/issues/372 so I will close this one.

Best regards,
Onur

**Closed by Celebio** 2018-12-04 16:02 UTC
