### ISSUE TITLE
duplicate words in pre-trained model

### ISSUE THREAD

**Issue by SilverGuo** [facebookresearch/fastText#167] opened 2017-03-09 16:21 UTC
Hi,

Thanks for your pre-trained model, it's really great.

I load the English vec file with following code:
```
# load by text file
vocab_freq = []
with open('./wiki.en/wiki.en.vec', 'r', encoding='utf-8') as f:
    print(f.readline())
    for line in f.readlines():
        vocab_freq.append(line.split()[0])
```
vocab_freq is the list of words in frequence order
```
print(len(vocab_freq))
print(len(set(vocab_freq)))
```
it returns
```
2519370
2518843
```
That means it contains nearly 500 duplicate words

It's normal or not? Thx.

**Comment by petr-tik** [comment] 2017-04-23 22:19
the word2vec corpus also has duplicates, which might suggests this is a feature, not a bug. 

Still would be great to get clarity from the authors. 

What are we supposed to do for duplicate words? Which vector do we discard?

**Comment by lgalke** [comment] 2017-04-28 13:38
I had a closer look on this. It seems that this behaviour is caused by pythons `split` method.
``` python
with open(sys.argv[1], 'r') as f:
    vocab = set()
    for i, line in enumerate(f):
        word = line.split(' ')[0]
        if word in vocab:
            print("Found duplicate:", word)
            print("In line %d:" % (i+1), line)
        else:
            vocab.add(word)
    print(len(vocab))
```
Without `' '` as argument to split, I get duplicates, while in the present version, I do not get any duplicates.
I had a closer look at one example: `pp` and ` pp` where ` ` is actually `U+202F NARROW NO-BREAK SPACE`. I assume that `.split()` without arguments treats it as a space(-like) character, which results in a duplicate entry with plain `pp`.

Just for the record, I got `2519370` distinct entries, when I split the line on explicit whitespace.

**Comment by elbamos** [comment] 2017-05-01 15:16
I'm pretty sure this doesn't matter -- fastText uses the hashing trick for vocabulary.  So it doesn't matter how many times the same word appears as distinct entries in the dictionary, it'll still be the same vector.  

See https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L37

**Comment by SilverGuo** [comment] 2017-05-09 14:49
@lgalke thx for your idea, it is really interesting.

but for example, why fastText treat 'the' and '<space>the' as two distinct words?

**Comment by SilverGuo** [comment] 2017-05-09 14:51
@elbamos if I understand correct, you will get the same vector if you load the model by .bin file.

but if you read the txt file, you will find the vector for 'the' and '<space>the' are different.

**Comment by lgalke** [comment] 2017-05-09 15:25
@SilverGuo The issue is originated in the UTF-8 encoding, there is:
- `U+0020 SPACE`
- `U+202F NARROW NO-BREAK SPACE`

Obviously, during training the latter one is treated as part of the word while the former is a proper token seperator. Long story short: You will always get the same vector, when you query for 'the'.
Just in the rare case, where you query for `<U+202F NARROW NO-BREAK SPACE>the`, you would give the different ones. So there are **no** multiple vectors for the same term, but the difference in the terms is at some point not visible (you will typically not notice a narrow non-breaking space instead of a usual space). 

For`the` example: I had a quick look: the following word vectors are provided:

- `the`
- `#the`
- `the%`
- `<U+2014 EM DASH>the`
-  `<U+2018 LEFT SINGNLE QUOTATION MARK>the`
- `/the`
- `}}the`
- `,the`
- `com/the`
- ...

**Comment by petr-tik** [comment] 2017-05-09 15:32
Thanks @lgalke

Time to re-read
http://www.joelonsoftware.com/articles/Unicode.html

**Comment by SilverGuo** [comment] 2017-05-10 07:13
Thanks @lgalke @petr-tik @elbamos 
It's clear for me now:)

**Comment by cpuhrsch** [comment] 2017-07-03 23:08
Looks like @lgalke's answer is exactly right. Closing this issue now.

**Closed by cpuhrsch** 2017-07-03 23:08 UTC
