### ISSUE TITLE
multi-thread not work

### ISSUE THREAD

**Issue by OpenWaygate** [facebookresearch/fastText#1058] opened 2020-05-02 07:15 UTC
I have set `-thread 6` but `htop` shows that only one core used.
```
  1  [||                                            1.3%]   4  [                                              0.0%]
  2  [                                              0.0%]   5  [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  3  [|                                             0.7%]   6  [                                              0.0%]
  Mem[|||||||||||||||||||||||                2.54G/15.6G]   Tasks: 68, 99 thr; 2 running
  Swp[||||||||||||||||||||||||                 453M/976M]   Load average: 0.93 0.57 0.74
                                                            Uptime: 1 day, 02:11:06
```
It is strange because I remember multi-thread used to work.

**Comment by Celebio** [comment] 2020-05-04 08:54
Hi @OpenWaygate ,
I can't reproduce the issue, I can see all the threads in htop. Which version are you using? Could you provide a little bit more context?

Best regards,
Onur

**Comment by OpenWaygate** [comment] 2020-05-04 10:51
My command
```
nohup fasttext supervised -input text.train -output model -dim 300 -loss ova -thread 6 -pretrainedVectors pretrained.vec -autotune-validation text.valid -autotune-duration 3600> log 2>&1 </dev/null &
```

After observation, I find that most of the time only 1 CPU core used, only when a trial is near end will all 6 cores used,  

```
Progress:  56.6% Trials:   4 Best score:  0.816744 ETA:   20m27s  // Trial 4 end, 6 core used
Progress:  56.7% Trials:   5 Best score:  0.816744 ETA:   20m26s  // Trial 5 start, 1 core used
...
Progress:  66.6% Trials:   5 Best score:  0.816744 ETA:   15m26s  // Trial 5 near end, 6 core used
...
Progress:  67.6% Trials:   5 Best score:  0.816744 ETA:   15m 6s  // Trial 5 end, 6 core used
Progress:  67.7% Trials:   6 Best score:  0.816744 ETA:   15m 5s  // Trial 6 start, 1 core used
```

**Comment by Celebio** [comment] 2020-06-02 12:54
Hi @OpenWaygate ,
Autotune loop itself uses only one thread, but each training trial uses multi-threading. I believe when you look at the used threads, it comes at a time when you are in the autotune loop.

I will close the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur

**Closed by Celebio** 2020-06-02 12:54 UTC
