### ISSUE TITLE
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more(fasttext 0.9.2)

### ISSUE THREAD

**Issue by miladfa7** [facebookresearch/fastText#1056] opened 2020-04-29 21:40 UTC
`model = fasttext.load_model("model_pretrain.ftz")`

Warning: `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

What is this warning for?

**Comment by Celebio** [comment] 2020-05-05 09:27
Hi @miladfa7 ,
This is just a deprecation warning, related to compatibility with older versions of a python library (more information [here](https://fasttext.cc/blog/2019/06/25/blog-post.html)). You can safely ignore this warning.

I will close the issue, feel free to re-open it if you need any further information.

Best regards,
Onur

**Closed by Celebio** 2020-05-05 09:27 UTC

**Comment by jypatel20** [comment] 2020-05-15 16:20
when I load the a supervised text classification model back after saving it, it predicts only 1 label. I get the same warning, on the other hand, if the model is trained, and then used for prediction, it performs normally.

**Comment by OAdesanya** [comment] 2020-08-08 23:48
Using the following step in documentation rather than `pip install fasttext` seems to solve the problem.
```
$ git clone https://github.com/facebookresearch/fastText.git
$ cd fastText
$ sudo pip install .
$ # or :
$ sudo python setup.py install
```

**Comment by evrial** [comment] 2021-03-04 12:22
Guys, are you retarded? Why documented piece of trivial code throws unignoreable deprecations? Please try to explain.

**Comment by evrial** [comment] 2021-03-04 12:33
Really pathetic that whole 10 months still you didn't merge fix commit into package release https://github.com/facebookresearch/fastText/commit/9ef22d9fac33c84480fa2e4edf56df13cb0bcfbb

**Comment by maayanorner** [comment] 2021-07-12 09:17
Until they release a new version, you can use py.io (or implement yourself, but it's messy since it's not pure Python and redirect_stdout is not working as expected) to suppress the message.
```
import py.io

def get_model():
    capture = py.io.StdCaptureFD(out=False, in_=False)
    model = fasttext.load_model(model_p)
    out, err = capture.reset()
    # Handle err here...
    return model
```

**Comment by evrial** [comment] 2021-07-12 09:29
rip fasttext

**Comment by sanderland** [comment] 2022-03-24 09:09
```
try:
    # silences warnings as the package does not properly use the python 'warnings' package
    # see https://github.com/facebookresearch/fastText/issues/1056
    fasttext.FastText.eprint = lambda *args,**kwargs: None
except:
    pass
```

**Comment by SHi-ON** [comment] 2022-10-13 19:06
Just use the _FastText class instance directly:

```python
from fasttext.FastText import _FastText

...

ft_model = _FastText(model_path=MODEL_PATH)

```
This is not definitely the perfect way, as the class is defined as a protected member, however that's only because of the way this library is structured.

**Comment by mossadhelali** [comment] 2022-10-22 04:11
I am also facing this issue. In my case, I launch multiple processes and use fasttext in each process. This leads to my output being cluttered with this warning. 
Also, a warning should be given to the user only when they fail to use the package properly. Using the package as intended should never give a warning.

**Comment by rajeshkppt** [comment] 2023-10-22 14:57
I see this error with python 3.12 as well
