### ISSUE TITLE
the word represent problem

### ISSUE THREAD

**Issue by yuquanle** [facebookresearch/fastText#237] opened 2017-06-03 11:22 UTC
hi everyone
    I have use fastText to train the wiki word embedding model. when I finished, I find the each dimension of word vector is more than 1. That is different for word2vec and glove.
   My problem is that I use compute-accuracy.c which is provided in word2vec tool to compute the accuracy of model which is trained by fastText ,the accuracy is zero. And the cosine similarity of word vector which uses fastText trained  if range -1 to 1 like word2vec model or glove model?

                                                                                                                                 Thank yours very much.
                                                                                                                                                  yuquanle

**Comment by cpuhrsch** [comment] 2017-07-04 20:29
Hello @yuquanle,

I've looked at both word2vec and glove vectors and I find that various vectors have entries larger than 1. Since you're getting zero accuracy for the fastText vectors, could you post the steps you took to reproduce the issue? 

The cosine similarity between two vectors, [by definition, will always be bounded by -1 and 1](https://en.wikipedia.org/wiki/Cosine_similarity#Definition). This is independent of the norm of the vectors or any prior scalar multiplication across all dimensions.

I'm closing this issue now to indicate that it has been answered. Please feel free to reopen it if this answer isn't sufficient.

Thanks,
Christian

**Closed by cpuhrsch** 2017-07-04 20:29 UTC
