### ISSUE TITLE
why the result (precision and recall) is nan  in Python3.5

### ISSUE THREAD

**Issue by tianyunzqs** [facebookresearch/fastText#192] opened 2017-05-02 06:15 UTC
some uncommon result showed as follow (but no error) when fasttext used.
The version of Python is 3.5
I get the result as follow with the introduction in https://github.com/miguelgfierro/sciblog_support/blob/master/Intro_to_NLP_with_fastText/Intro_to_NLP.ipynb
does anyone know how to fix it ?

-------uncommon result-------
3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
P@1: nan
R@1: nan
Number of examples: 0

**Comment by cpuhrsch** [comment] 2017-05-03 17:14
Hey @tianyunzqs,

I'm not sure if I can be of help here unfortunately, since you're referencing a file that is outside of this repository. Have you tried contacting the associated maintainers?

Best
Christian

**Comment by zhongboyin** [comment] 2017-05-06 03:38
I have no idea yet, that is my test result: who knows how to solve this problem ?
./fasttext test model.bin /##/test.txt k
N	0
P@0	nan
R@0	nan
Number of examples: 0

**Comment by brightmart** [comment] 2017-05-20 14:58
i also get these two nan at first trial. later it was sloved by:
1) make sure there is a space between training sentence and label. for example, 'i am fine __label__good '
2)if you lable is a long, and have many words, you can use hash(label) to get number label, which is only a single word. for example,label:'xxx/yyy/zzz', after hash('xxx/yyy/zzz'), it is '23442343243'

**Comment by tianyunzqs** [comment] 2017-05-22 12:12
@brightmart 
I have done in the way you told, but the result is no changed. Can you give me your code to reference? 
Thanks
By the way, I install the fasttext with ''pip install fasttext''

**Comment by cpuhrsch** [comment] 2017-05-29 03:11
Hello @brightmart, @tianyunzqs, @zhongboyin, please follow up with the author of the python bindings regarding this issue. I'm going to close this issue for now, but please feel free to reopen, if the issue can be traced back to the fastText binary itself.

**Closed by cpuhrsch** 2017-05-29 03:11 UTC

**Comment by sibi123** [comment] 2017-06-10 15:16
Hi cpuhrsch,

I have the same issues (as mentioned above), the question remains, how do i use fasttext in my python project. Do you have any examples/tutorials on this. i installed it by 'pip install fasttext' and then i use the 'fasttext.supervised' function to train, which executes without giving an error. But, the problem is that 
 later i get 
P@1: nan
R@1: nan
Number of examples: 0

**Comment by StephenLee2016** [comment] 2017-06-12 01:51
Hello @sibi123 , I met the same issues in python3.5 , but when i use python2.7 i got the rigth result.

**Comment by tianyunzqs** [comment] 2017-07-07 08:51
@zhongboyin @sibi123 
i have found the reason, it because fasttext package can train in windows OS, but it can't predict. 
if you take the experiment in Liunx, it will give the right answer.

**Comment by phuonglv6** [comment] 2019-02-25 10:34
i have found the same issue. i have alread resolved the problem is wrong data format i wrote __Label__ insteal of __label__
