### ISSUE TITLE
Python method to get nearest neighbor vectors for a vector

### ISSUE THREAD

**Issue by johann-petrak** [facebookresearch/fastText#1069] opened 2020-05-13 15:32 UTC
The method "get_nearest_neighbors" can only be applied to a word, not to a vector. However, for a calculated vector (e.g. an average vector) it would be good to get the N closest vectors to the given vector. 

Apparently this was possible with the now deprecated library pyfasttext but the new library seems to lack quite a number of useful methods. 

(and it does not seem to have a `fasttext.__version__` declared.)

**Comment by Celebio** [comment] 2020-06-02 10:32
Hi @johann-petrak ,
Thank you very much for your message. I understand the deprecated version of the python module had this feature. One way to handle that would be keep track of the word corresponding to the vector and use the current api. The other way will be to use a regular k-nn algorithm on the input matrix (with `get_input_matrix`).

I will add this as a feature request to our roadmap, I will also note your feedback on `__version__` property.

I will close the issue now. Feel free to re-open it if you have further questions.
Thank you again for feedback.

Onur

**Closed by Celebio** 2020-06-02 10:32 UTC
Labels: Feature request

**Comment by ginward** [comment] 2020-08-09 15:02
I agree that adding this feature would be very helpful!

**Comment by reinoldus** [comment] 2021-04-12 14:53
Is this still being considered?

**Comment by hiyamgh** [comment] 2022-02-12 13:23
Is the feature implemented yet?

**Comment by johann-petrak** [comment] 2022-02-12 19:25
Looks like this project is dead or abandoned, there have been no commits, let alone releases since I posted that feature request.
New issues have been left unanswered since then. 
Sadly the README has not been updated to inform users what the status is. 

Adding this feature should actually have been quite trivial because all the necessary code MUST already be there: NN for words works by getting the vectors for the words getting NNs based on the vectors, then translating back to works. All that would have been needed is give public API access to that code so that vectors can be used directly.

**Comment by kasnerz** [comment] 2023-11-06 16:09
I implemented [this change](https://github.com/facebookresearch/fastText/commit/87c23ba4fd7906db1000784299d5642b59bdde10) in [my fork](https://github.com/kasnerz/fastText). Even though the issue is closed, I assume it may still come in handy to somebody.

The method `get_nearest_neighbors_embedding()` is identical to `get_nearest_neighbors()`, only that it accepts a `np.array` with the embedding vector instead of `str`.

**Comment by johann-petrak** [comment] 2023-11-06 17:29
Thank you, @kasnerz  

Pity that facebookresearch did not go forward on this since 2020 but closed the issue (althoug the issue has NOT been solved in this repo) which I think is not the best way to deal with feature requests.
