### ISSUE TITLE
Compilation error in OSX

### ISSUE THREAD

**Issue by zhigangc** [facebookresearch/fastText#349] opened 2017-11-02 08:29 UTC
$ clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

$ python setup.py build
running build
running build_py
running build_ext
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jerryzchen/.vpy/pydev3/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /var/folders/46/pv448hmj48nd3kc0mjsybpx40000gn/T/tmpv1dkg3ai.cpp -o var/folders/46/pv448hmj48nd3kc0mjsybpx40000gn/T/tmpv1dkg3ai.o -std=c++14
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jerryzchen/.vpy/pydev3/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c /var/folders/46/pv448hmj48nd3kc0mjsybpx40000gn/T/tmpi9n95pu6.cpp -o var/folders/46/pv448hmj48nd3kc0mjsybpx40000gn/T/tmpi9n95pu6.o -fvisibility=hidden
building 'fasttext_pybind' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jerryzchen/.vpy/pydev3/include/site/python3.6 -I/Users/jerryzchen/.vpy/pydev3/include/site/python3.6 -I../src -I/Users/jerryzchen/.vpy/pydev3/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c fastText/pybind/fasttext_pybind.cc -o build/temp.macosx-10.12-x86_64-3.6/fastText/pybind/fasttext_pybind.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="0.0.1" -std=c++14 -fvisibility=hidden
In file included from fastText/pybind/fasttext_pybind.cc:11:
../src/fasttext.h:31:9: warning: getVector is being deprecated and replaced by getWordVector. [-W#pragma-messages]
#pragma message("getVector is being deprecated and replaced by getWordVector.")
        ^
fastText/pybind/fasttext_pybind.cc:89:16: error: no matching constructor for initialization of 'py::buffer_info'
        return py::buffer_info(
               ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:28:5: note: candidate constructor not viable: cannot convert initializer list argument to
      'detail::any_container<ssize_t>' (aka 'any_container<long>')
    buffer_info(void *ptr, ssize_t itemsize, const std::string &format, ssize_t ndim,
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:39:5: note: candidate constructor template not viable: requires 3 arguments, but 6 were
      provided
    buffer_info(T *ptr, detail::any_container<ssize_t> shape_in, detail::any_container<ssize_t> strides_in)
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:46:5: note: candidate constructor template not viable: requires 2 arguments, but 6 were
      provided
    buffer_info(T *ptr, ssize_t size)
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:83:5: note: candidate constructor not viable: requires 7 arguments, but 6 were provided
    buffer_info(private_ctr_tag, void *ptr, ssize_t itemsize, const std::string &format, ssize_t ndim,
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:42:5: note: candidate constructor not viable: requires 4 arguments, but 6 were provided
    buffer_info(void *ptr, ssize_t itemsize, const std::string &format, ssize_t size)
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:49:14: note: candidate constructor not viable: requires at most 2 arguments, but 6 were
      provided
    explicit buffer_info(Py_buffer *view, bool ownview = true)
             ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:56:5: note: candidate constructor not viable: requires 1 argument, but 6 were provided
    buffer_info(const buffer_info &) = delete;
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:59:5: note: candidate constructor not viable: requires single argument 'other', but 6
      arguments were provided
    buffer_info(buffer_info &&other) {
    ^
/Users/jerryzchen/.vpy/pydev3/include/site/python3.6/pybind11/buffer_info.h:26:5: note: candidate constructor not viable: requires 0 arguments, but 6 were provided
    buffer_info() { }
    ^
fastText/pybind/fasttext_pybind.cc:151:35: warning: comparison of integers of different signs: 'int32_t' (aka 'int') and 'std::__1::vector<long long,
      std::__1::allocator<long long> >::size_type' (aka 'unsigned long') [-Wsign-compare]
            for (int32_t i = 0; i < vocab_freq.size(); i++) {
                                ~ ^ ~~~~~~~~~~~~~~~~~
fastText/pybind/fasttext_pybind.cc:165:35: warning: comparison of integers of different signs: 'int32_t' (aka 'int') and 'std::__1::vector<long long,
      std::__1::allocator<long long> >::size_type' (aka 'unsigned long') [-Wsign-compare]
            for (int32_t i = 0; i < labels_freq.size(); i++) {
                                ~ ^ ~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
error: command 'clang' failed with exit status 1

**Comment by zhigangc** [comment] 2017-11-02 08:39
I have the fix:

diff --git a/python/fastText/pybind/fasttext_pybind.cc b/python/fastText/pybind/fasttext_pybind.cc
index 88eecb4..028c8d4 100644
--- a/python/fastText/pybind/fasttext_pybind.cc
+++ b/python/fastText/pybind/fasttext_pybind.cc
@@ -92,7 +92,7 @@ PYBIND11_MODULE(fasttext_pybind, m) {
             py::format_descriptor<fasttext::real>::format(),
             2,
             {m.m_, m.n_},
-            {sizeof(fasttext::real) * m.n_, sizeof(fasttext::real)});
+            {sizeof(fasttext::real) * m.n_, sizeof(fasttext::real) * (int64_t)1});
       });
 
   py::class_<fasttext::FastText>(m, "fasttext")

**Comment by cpuhrsch** [comment] 2017-11-02 16:12
Hey @zhigangc,

Thank you for your post! I've indeed been able to reproduce this. I'm sending out the fix!

Thanks,
Christian

**Comment by cpuhrsch** [comment] 2017-11-02 16:52
The fix has been pushed, please try again!

**Comment by cpuhrsch** [comment] 2017-11-15 04:41
Hey @zhigangc,

Closing this now as it has been 2 weeks since the fix has pushed. Please feel to reopen at any point.

Thanks,
Christian

**Closed by cpuhrsch** 2017-11-15 04:41 UTC
